### ISSUE TITLE
tensorflow版本

### ISSUE THREAD

**Issue by guxing119** [bubbliiiing/ssd-tf2#2]
楼主你好，看了你的代码，predict.py中还存在清session的代码, utils.py里面还存在错误（eg: wraning找不到），麻烦确认一下是否为tf2.0版, 还是在原来tf1.0的版本改过来的时候漏改了，谢谢！

**Comment by bubbliiiing** [comment]
漏改了

**Comment by bubbliiiing** [comment]
tf2.2版本

**Comment by bubbliiiing** [comment]
utils.py的错误应该是你环境配置上的小问题，因为我是有单独的tf2环境的，里面没有任何keras和tf1的内容

**Comment by guxing119** [comment]
楼主您好，感谢您的回答，刚才看了一下，utils.py中是由于没有import warnings所以在使用warnings的时候会报错。望修正，谢谢！

另外有个问题想请教一下。
跑训练的时候，报了以下错误，麻烦您能帮忙看一下吗？谢谢！
数据集用的VOC2007
Train for 4510 steps, validate for 501 steps
Epoch 1/25
2020-07-27 18:20:03.244965: I tensorflow/core/profiler/lib/profiler_session.cc:184] Profiler session started.
Traceback (most recent call last):
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 681, in on_epoch
    yield epoch_logs
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 503, in _call
    self._initialize(args, kwds, add_initializers_to=initializer_map)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 408, in _initialize
    *args, **kwds))
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1848, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2150, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 2041, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/framework/func_graph.py", line 915, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/eager/def_function.py", line 358, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 73, in distributed_function
    per_replica_function, args=(model, x, y, sample_weights))
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 760, in experimental_run_v2
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1787, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/distribute/distribute_lib.py", line 2132, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 264, in train_on_batch
    output_loss_metrics=model._output_loss_metrics)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 311, in train_on_batch
    output_loss_metrics=output_loss_metrics))
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 252, in _process_single_batch
    training=training))
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_eager.py", line 127, in _model_loss
    outs = model(inputs, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 708, in call
    convert_kwargs_to_constants=base_layer_utils.call_context().saving)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 860, in _run_internal_graph
    output_tensors = layer(computed_tensors, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 847, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/Users/liuyubin/anaconda3/envs/deep_learning/lib/python3.6/site-packages/tensorflow_core/python/autograph/impl/api.py", line 292, in wrapper
    return func(*args, **kwargs)
  File "/Users/liuyubin/Documents/MyWorkspace/Python/ai_projects/bilibili_up/tensorflow2_ssd/nets/ssd_layers.py", line 111, in call
    step_x = img_width / layer_width
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'

说的是，在获取先验框的时候，无法取得各个有效特征层的宽高。debug了一下，确实是在调用call方法时，参数x的值得shape为(None, None, None, 512), 这里应该是net['conv4_3_norm']的shape(None, 38, 38, 512), 不知道为什么, (38,38)无法取得，取得的是(None, None) 麻烦您，谢谢！

**Comment by bubbliiiing** [comment]
要么你装个2.2试试？

**Comment by guxing119** [comment]
楼主你好，果然是版本问题, 开始我在mac上跑的，查了查，mac最大支持到2.0，换了个环境，就可以了，添麻烦了，多谢！

2020-07-27 11:07:26.007587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.73GiB deviceMemoryBandwidth: 298.08GiB/s
2020-07-27 11:07:26.007629: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-27 11:07:26.009482: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-27 11:07:26.011165: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-27 11:07:26.011528: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-27 11:07:26.013472: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-27 11:07:26.014621: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-27 11:07:26.018172: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-27 11:07:26.018307: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.018918: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.019461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-27 11:07:26.644546: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2200000000 Hz
2020-07-27 11:07:26.644750: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ce6bc0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-07-27 11:07:26.644789: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-07-27 11:07:26.755111: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.756071: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1ce6d80 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-07-27 11:07:26.756107: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-07-27 11:07:26.756343: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.757222: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.73GiB deviceMemoryBandwidth: 298.08GiB/s
2020-07-27 11:07:26.757278: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-27 11:07:26.757346: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-27 11:07:26.757380: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-27 11:07:26.757401: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-27 11:07:26.757420: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-27 11:07:26.757439: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-27 11:07:26.757458: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-27 11:07:26.757537: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.758208: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:26.758755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-07-27 11:07:26.758805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-27 11:07:27.283300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-27 11:07:27.283370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-07-27 11:07:27.283400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-07-27 11:07:27.283598: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:27.284199: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-07-27 11:07:27.284773: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13970 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2020-07-27 11:07:28.733087: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
2020-07-27 11:07:28.733161: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1363] Profiler found 1 GPUs
2020-07-27 11:07:28.733974: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcupti.so.10.1
2020-07-27 11:07:28.835520: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1479] CUPTI activity buffer flushed
Epoch 1/25
2020-07-27 11:07:40.762919: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-27 11:07:45.915494: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-27 11:07:51.277061: I tensorflow/core/profiler/lib/profiler_session.cc:159] Profiler session started.
  1/281 [..............................] - ETA: 0s - loss: 4.00132020-07-27 11:07:51.477306: I tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1479] CUPTI activity buffer flushed
2020-07-27 11:07:51.477640: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:216]  GpuTracer has collected 693 callback api events and 693 activity events.
2020-07-27 11:07:51.511243: I tensorflow/core/profiler/rpc/client/save_profile.cc:168] Creating directory: logs/train/plugins/profile/2020_07_27_11_07_51
2020-07-27 11:07:51.525389: I tensorflow/core/profiler/rpc/client/save_profile.cc:174] Dumped gzipped tool data for trace.json.gz to logs/train/plugins/profile/2020_07_27_11_07_51/6abc6edfae8e.trace.json.gz
2020-07-27 11:07:51.532754: I tensorflow/core/profiler/utils/event_span.cc:288] Generation of step-events took 0.244 ms
